///id, type, other_stats
inv_itm_stt[0] = argument0;//id
inv_itm_stt[1] = argument1;//type
inv_itm_stt[2] = argument2;//name
inv_itm_stt[3] = argument3;//lore
inv_itm_stt[4] = argument4;//state
inv_itm_stt[5] = argument5;//number
inv_itm_stt[6] = argument6;//state
inv_itm_stt[7] = argument7;//number
inv_itm_stt[8] = argument8;//state
inv_itm_stt[9] = argument9;//number
inv_itm_stt[10] = argument10;//state
inv_itm_stt[11] = argument11;//number
inv_itm_stt[12] = argument12;//state
inv_itm_stt[13] = argument13;//number
inv_itm_stt[14] = argument14;//state
inv_itm_stt[15] = argument15;//number
